### ISSUE TITLE
SQLite user dashboard's left nav dropdowns should not be clickable

### ISSUE THREAD

**Issue by unatarajan** [sqlitecloud/sqlitecloud-js#101]
# Validation/ Reproduction Steps

1. Log into your SQLite Cloud account.
2. In the left nav, "Databases" and "Development" are links themselves AND accordions containing more links. This is inconsistent because "Security" and "Advanced" are accordions containing more links but are NOT links themselves.

## Suggested Fix

Remove the links behind "Databases" and "Development" and move them into the accordions.

## Screenshots & Videos
<img width="753" alt="Screenshot 2024-07-09 at 1 27 32 PM" src="https://github.com/sqlitecloud/private-issues/assets/38731992/e17e591b-834e-45e2-8b37-79fb6c0f0e62">
<img width="723" alt="Screenshot 2024-07-09 at 1 27 44 PM" src="https://github.com/sqlitecloud/private-issues/assets/38731992/05c80c14-506d-4198-a32d-2e32a803d08c">

**Comment by TizianoT** [comment]
wip2.sqlitecloud.io

We are working on a new ui left nav.
You cam try that at the link above. 

The situation described is not present anymore.

**Comment by jacobprall** [comment]
Good catch @unatarajan we have a pr in works to fix this :)

**Comment by unatarajan** [comment]
Hi @TizianoT - Since the link is to a non-production environment, do I need to create a new account/ login?

**Comment by jacobprall** [comment]
Will improve in other ticket, thank you for opening :)
