### ISSUE TITLE
tests -> create automatically databases that aren't chinook

### ISSUE THREAD

**Issue by Gioee** [sqlitecloud/sqlitecloud-js#172]
## Current Behavior

Some tests use other dbs like people.sqlite which aren't created by default when there's a creation of a new node

## Expected Behavior

When tests use other dbs they should also create them

## Steps to Reproduce the Problem

  1. Run `npm run test` in a new node

**Comment by danielebriggi** [comment]
@Gioee when the issue is closed you can delete the database and see the testing working
