### ISSUE TITLE
Querying sqlite_master in the last driver version returns null

### ISSUE THREAD

**Issue by Gioee** [sqlitecloud/sqlitecloud-js#176]
I've found out the issue

Querying sqlite master from driver 1.0.289
![screenshot_2024-12-17_alle_09 37 00_720](https://github.com/user-attachments/assets/b53978cc-282c-4c0e-8fcc-b0bf7d1e8db6)

Querying sqlite master from driver 1.0.345
![screenshot_2024-12-17_alle_09 38 36_720](https://github.com/user-attachments/assets/311984f8-9e61-4e4f-934f-24665f668665)

_Originally posted by @Gioee in https://github.com/sqlitecloud/dashboard/issues/368#issuecomment-2547818098_

**Comment by Gioee** [comment]
@danielebriggi has the driver in the production dashboard been updated?

**Comment by danielebriggi** [comment]
I closed it because the code is in the master branch
