### ISSUE TITLE
Driver can't connect using plain Javascript

### ISSUE THREAD

**Issue by toyosee** [sqlitecloud/sqlitecloud-js#65]
## Current Behavior

When connecting to the database, it returns an error after a delay. Time out error.
SQLiteCloudConnection.connect - error connecting clwb0uytsk.sqlite.cloud:8860 SQLiteCloudError: Request timed out SQLiteCloudError: Request timed out
    at Timeout._a (C:\Users\User\Desktop\sqlitecloud-js-main\node_modules\@sqlitecloud\drivers\lib\drivers\connection-tls.js:210:38)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  cause: '+86 AUTH USER ****** PASSWORD ******; USE DATABASE chinook.sqlite; '
}
SQLiteCloudConnection.connect - error connecting clwb0uytsk.sqlite.cloud:8860 SQLiteCloudError: Request timed out SQLiteCloudError: Request timed out
    at Timeout._a (C:\Users\User\Desktop\sqlitecloud-js-main\node_modules\@sqlitecloud\drivers\lib\drivers\connection-tls.js:210:38)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  cause: '+86 AUTH USER ****** PASSWORD ******; USE DATABASE chinook.sqlite; '
}
node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^

SQLiteCloudError: Request timed out
    at Timeout._a (C:\Users\User\Desktop\sqlitecloud-js-main\node_modules\@sqlitecloud\drivers\lib\drivers\connection-tls.js:210:38)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  cause: '+86 AUTH USER ****** PASSWORD ******; USE DATABASE chinook.sqlite; '
}

Node.js v20.6.1
This error returns when using the shipped html interface to test the database/gateway connection
Messages:

    connect_error | reason: xhr poll error
    connect_error | reason: xhr poll error

## Expected Behavior

I expect to get a response of the queried table. And to see my connection on the  node. the node ip returned 0.0.0.0 all the time.
I updated my environment variable and connection string in order to use the web form. I got a connection error

## Steps to Reproduce the Problem

  1. New index file in root folder of Javascript SDK, set the module in package.json to be able to load the sqlite driver
  1. node filename.js connection time out after a long time of wait
  1. updated variables in the env file tto be able to use the driver.html and gateay.html. Gateway returned a message of connected, driver returned a connection error as described above

## Environment

- Version: 
- "@sqlitecloud/drivers": "^0.0.50"
- Platform: 
- Windows
- Node.js Version: 
- v20.6.1

**Comment by gionatamettifogo** [comment]
Hi @toyosee 

Can you update the driver to the latest version? I just committed updated examples of plain javascript connections, connecting with express, connecting with Typescript and with Knex ORM.
https://github.com/sqlitecloud/sqlitecloud-js/releases/tag/v0.0.56

Let me know if you still have problems.

Thanks,
--gio

**Comment by toyosee** [comment]
Thank you for your prompt response and the update. Now i can reach the database and error is resolved with the latest update. I am left with a question concerning the gateway variables in the env. # sqlite cloud gateway for socket.io connections
GATEWAY_URL=ws://localhost:4000  Is this a default value or each node has its particular gateway url?
If so, i have checked the documentation and my node, unable to find the gateway url

**Comment by gionatamettifogo** [comment]
Yes, each node has its own gateway. If your node is, let say:
```sqlitecloud://admin:xxx@nitey2ltiz.sqlite.cloud:8860```

![Screenshot 2024-02-29 at 07 53 29](https://github.com/sqlitecloud/sqlitecloud-js/assets/2813336/f4ffa489-c578-4a64-a2be-4b6ffa5ffec4)


Then your gateway will be:
```wss://nitey2ltiz.sqlite.cloud:4000```

We do need to updated the documentation, I'll make a note of it, thanks.

**Comment by toyosee** [comment]
@gionatamettifogo 
Thank you for your prompt response. I am glad i pointed the issue out for documentation. I have effected the changes on the env and on form as well, i now have a different error message. Timeout.
Messages:

    connect_error | reason: xhr poll error
    connect_error | reason: timeout
    connect_error | reason: timeout

This was a similar error to what i experience when using node before you sent an updated SDK to me.

**Comment by gionatamettifogo** [comment]
Are you connecting from node? from the browser?

If you connect from node you don't need to use the gateway at all, you can just connect straight to the database.
