### ISSUE TITLE
Insert data is not returned when using pre-prepared statements

### ISSUE THREAD

**Issue by ewanhowell1** [sqlitecloud/sqlitecloud-js#71]
## Current Behavior

Pre-prepared statements return nothing

## Expected Behavior

Pre-prepared statements return the insert data

## Steps to Reproduce the Problem

```js
console.log(await database.sql("INSERT INTO agents (email) VALUES ('test')"))
// { lastID: 9, changes: 1, totalChanges: 1, finalized: 1 }
```
```js
const statement = database.prepare("INSERT INTO agents (email) VALUES ('test2')")
statement.run((err, res) => console.log(res))
// undefined
```

## Environment

- Version: 0.0.56
- Platform: Win
- Node.js Version: v20.12.2

**Comment by gionatamettifogo** [comment]
Thanks Ewan, I will look into this and get back to you asap.

**Comment by gionatamettifogo** [comment]
Hi @ewanhowell1,

I changed the driver to report the number of changes as a result when calling a prepared statement's run method (previously these same value were returned as context and still are). Also write a quick test example to how how the statement is prepared and executed:

```js
it('Statement.run - with insert results', done => {
  // create simple "people" database that we can write in...
  const database = getTestingDatabase(error => {
    expect(error).toBeNull()

    const statement = database.prepare('INSERT INTO people (name, hobby, age) VALUES (?, ?, ?); ')

    // @ts-ignore
    statement.run('John Wayne', 73, 'Horse Riding', (error, results) => {
      // this is an insert statement and the result will indicate number of changes, etc.
      // console.debug(`insert results: `, results)
      // -> insert results:  { lastID: 21, changes: 1, totalChanges: 21, finalized: 1 }

      expect(results.lastID).toBeGreaterThan(1)
      expect(results.changes).toBe(1)

      done()
    })
  })
  ```
  
  Still, unless you have legacy code, the easiest way is ``await database.sql`` as you suggested above.
  Please let me know if I can be of help. Closing the issue, please reopen if the problem persists.
  
  You will need to update the driver to the latest 1.0.122 version:
  https://www.npmjs.com/package/@sqlitecloud/drivers/v/1.0.122
